#!/usr/bin/env bash

if [ -n "${DROPBOX_API_TOKEN:-""}" ]; then
  if [ -d world ]; then
	app_url=${APP_URL:-"localhost"}
	curl $app_url
    echo "OAUTH_ACCESS_TOKEN=${DROPBOX_API_TOKEN}" > ~/.dropbox_uploader
    bin/dropbox_uploader.sh upload world/ minecraft/
  else
    echo "OAUTH_ACCESS_TOKEN=${DROPBOX_API_TOKEN}" > ~/.dropbox_uploader
    bin/dropbox_uploader.sh download minecraft/world
    cd ..
  fi
fi
