#!/usr/bin/env bash


heroku_url = "${HEROKU_URL:-localhost}"
curl $heroku_url

if [ -n "${DROPBOX_API_TOKEN:-""}" ]; then
  if [ -d world ]; then
    echo "OAUTH_ACCESS_TOKEN=${DROPBOX_API_TOKEN}" > ~/.dropbox_uploader
    bin/dropbox_uploader.sh upload world/ minecraft/
  else
    echo "OAUTH_ACCESS_TOKEN=${DROPBOX_API_TOKEN}" > ~/.dropbox_uploader
    bin/dropbox_uploader.sh download minecraft/world
    cd ..
  fi
fi
